### PR TITLE
#4140 Add preference to skip the loading of preset gif images.

### PR DESCRIPTION
**Pull request by derwin12**
Requested for folks that have a large number of presets. 
 The image is still created when an effect is added - it is simply not loaded when the preset tree is read.
 Preference added to the View panel. Default to false (off) ie it will be shown.

### CODE REVIEW

**Comment by derwin12** [comment]
I need to repush - seems my tabs are being translated to spaces?

**Comment by AzGilrock** [comment]
Yep tabs in code are usually frowned upon so I believe Git is converting them to spaces.

**Comment by AzGilrock** [comment]
You can usually setup your code editor to insert spaces when you hit the tab key.

**Comment by computergeek1507** [comment]
If you enable clang format in visual studio it should use the clang format file that defaults to spaces

**Comment by derwin12** [comment]
> If you enable clang format in visual studio it should use the clang format file that defaults to spaces

Something like this?
image

**Comment by computergeek1507** [comment]
You don't need power tools, it's built into vs2022 now

**Comment by computergeek1507** [comment]
image

**Comment by derwin12** [comment]
So I have this .. (your pic was cut off) - is it correct?
image
Also the profiles .. should I remove these bottom 3 or are they okay to add (seems like they should stay as they are the right thing to do)
image
image

**Comment by derwin12** [comment]
Now that I figured out how code::blocks gets involved here .. I updated the cb code and it injected into the commit.

**Pull request merged**
