### PR TITLE
Add Select Effects to the UI Toolbar #2444

### PR DESCRIPTION
**Pull request by derwin12**
I created some icons as well .. if anyone has thoughts on if it is ok or other ideas .. feel free to comment.

My thinking was to use the effects icon and the finger since that seems to be the usual icon for select.

image

I am not sure if there are any hidden things that need to be done/included for production rollout of a change like this.

### CODE REVIEW

**Comment by computergeek1507** [comment]
I'm Surprised that anymore uses this dialog I added

**Comment by dkulp** [comment]
Kind of wish we had svg's for all the icons... :(

**Comment by derwin12** [comment]
It is actually very handy for changing up stuff .. i can see power users using it quite a bit..

**Comment by dkulp** [comment]
> > Kind of wish we had svg's for all the icons... :(
> 
> Would they replace the icon files or in addition to them? I've only known one way to create the icons but I'm fairly good at creating vector art.

Eventually replace.   The BitmapBundle stuff that is now used in wxWidgets supports using SVG's instead of individually sized bitmaps.   That would (supposedly) allow arbitrary scaling of toolbar sizes and such while keeping the icons looking good.   Not sure it really matters though.

**Comment by kppankratz** [comment]
@dkulp - I emailed you the SVG files on 12/3/22 for the icons.   Should I resend?

**Comment by cybercop23** [comment]
People with the power.. can this please me merged?

**Pull request merged**
