### PR TITLE
Check that timing track name doesnt conflict with models #2785

### PR DESCRIPTION
**Pull request by derwin12**
If a timing track is named the same as a model, it is hidden. Checks were in place to catch a rename but were not done on the initial Add Timing track option. #2785

### CODE REVIEW

**Comment by derwin12** [comment]
oh for sure .. cant get them all but trying to close the one door...

**Comment by cybercop23** [comment]
SequenceElements/AddElement is called with "model" type that then calls ElementExists. We can pass _type_ to ElementExists and check that types also matches, thus allowing same names on different types, timingtracks, groups and models.
2 other functions will need to have the type added since they call ElementExists, but IMHo I don't think those 2 need to check at all - will be okay if we add the type, but maybe reduce a call.

**Comment by cybercop23** [comment]
> SequenceElements/AddElement is called with "model" type that then calls ElementExists. We can pass _type_ to ElementExists and check that types also matches, thus allowing same names on different types, timingtracks, groups and models. 2 other functions will need to have the type added since they call ElementExists, but IMHo I don't think those 2 need to check at all - will be okay if we add the type, but maybe reduce a call.

I was wrong... as usual.. at least ViewsModelsPanel need to have the check, else all modes will still show up on the left... small change.. but adding type.. seems to work...
image

**Comment by derwin12** [comment]
I believe there are a more than a few places where it assumes it is getting a sequence or a timing track when it does the lookup.  As Gil mentions .. we search by name. Would take going thru with a fine tooth comb.. Allowing both is a no-going-back change. Anybody using older versions could fall victim to duplicate names. I dont think many people actually hit this scenario .. ie naming a timing track the same as a model, so not sure it is worth the efforts.

**Comment by cybercop23** [comment]
Please tell me what else I should look at... new seq, views changes, adding/renaming TT and adding same name models works... I can try groups.. what else should I try?
YES... there may be crap out there not using this proper function, but what you found and what I looked at, they all use the ElementExists function, and that has been changed to account for type.

**Pull request merged**
