### PR TITLE
Add sub-model alias to info panel #4473

### PR DESCRIPTION
**Pull request by cybercop23**
Including the Aliases in the list....  for @computergeek1507 ... :)
image

### CODE REVIEW

**Comment by computergeek1507** [comment]
You could fix the the bug with a comma at the front of the node list while you're in there

**Comment by cybercop23** [comment]
> You could fix the the bug with a comma at the front of the node list while you're in there

Where's that issue? Not sure I know about it. Was looking for a until ListToCsl, but we don't have one. Maybe I'll create one for easier processing.

**Comment by cybercop23** [comment]
> You could fix the the bug with a comma at the front of the node list while you're in there

looking into fixing it too

**Comment by cybercop23** [comment]
@computergeek1507 all good?

**Comment by cybercop23** [comment]
@computergeek1507 you were right, as usual. That wasn't needed.
image

**Pull request merged**
