### PR TITLE
Add middle mouse to pan sequencer #4593

### PR DESCRIPTION
**Pull request by derwin12**
With a sequence open, on the sequence panel add the ability to middle click, hold and pan to move the sequence window. #4593

### CODE REVIEW

**Comment by derwin12** [comment]
Wait .. perhaps the action built version only included the 2nd commit .. so it only did the refactor in the .exe.
@computergeek1507 Scott - would that be the case? would it be the combined commits or just the last one that was sent in?

**Comment by cybercop23** [comment]
They'd had to be stacked.. else your 2 new functions, mouseMiddle[Down|Up] would have failed with no function definition, no?

**Comment by computergeek1507** [comment]
I think Alex found out that the pull request build is actually using master not the pull request id. I haven't fixed it.

**Comment by cybercop23** [comment]
> I think Alex found out that the pull request build is actually using master not the pull request id. I haven't fixed it.

ohh yeah.. forgot about that.... :)

**Comment by dkulp** [comment]
I merged this, but the two finger pan on the touchpad is WAY WAY smoother.   Likely should look closer at that as the base.

**Comment by derwin12** [comment]
> I merged this, but the two finger pan on the touchpad is WAY WAY smoother. Likely should look closer at that as the base.

I wonder if that is a wxwidget builtin shortcut to moving the bottom scrollbar. I didnt see any code there that did the two finger pan. I will investigate further.

**Comment by dkulp** [comment]
It's PROBABLY part of MainSequencer::mouseWheelMoved.

**Pull request merged**
