### PR TITLE
Keep buttons visible in submodel dialog #4568

### PR DESCRIPTION
**Pull request by derwin12**
Trigger the resize when the splitter is moved. #4568

### CODE REVIEW

**Comment by computergeek1507** [comment]
Looks like you neutered the stretchy grid class so it probably isn't needed anymore

**Comment by derwin12** [comment]
> Looks like you neutered the stretchy grid class so it probably isn't needed anymore

I did but couldnt really figure out how to remove it.. Feel free to grab the branch or maybe provide some howto?

**Comment by derwin12** [comment]
Removed the StretchGrid class .. the grid itself stretches cleanly with the splitter window event.

**Comment by computergeek1507** [comment]
In codeblocks change the class name to wxGrid

**Comment by derwin12** [comment]
Done .. thanks.

**Review by computergeek1507 — APPROVED** [review]

**Pull request merged**
