### PR TITLE
Increase size of DMX panels #2453 #3804

### PR DESCRIPTION
**Pull request by derwin12**
With many dmx props being 16 channels this makes it easier to see the entire list and remove the flipping back and forth when half are on one page and half on the other.
Also renamed one panel to be consistent and corrected the right justification in the channel list.
Increase from 40 to 48 as well since ending at 40 left a half panel.

### CODE REVIEW

**Comment by derwin12** [comment]
> I can’t merge it says there are conflicts to fix

I just resynced my repo - and that appears to have kicked off another conflict check. Let that finish and see how that goes.

**Comment by cybercop23** [comment]
People with the power.. can this please me merged?

**Comment by dkulp** [comment]
Needs to be re-based.

**Comment by derwin12** [comment]
I performed the rebase operation -- boy does this look messy. Did I do it wrong? Perhaps I should do another PR?

**Comment by dkulp** [comment]
> I performed the rebase operation -- boy does this look messy. Did I do it wrong? Perhaps I should do another PR?

From the command line, try a "git rebase origin/master" and then do a force push.   That should clean up most of that.

**Comment by derwin12** [comment]
I gather this is showing all the commits that took place from the time I started this branch to now. I will close this PR and just redo the code so that I can track exactly what is being done here.

**Pull request closed without merging**
