### PR TITLE
#4603 Add Reversed 3D fade on Single Strand

### PR DESCRIPTION
**Pull request by sidelights**
Allow for 3D fade to fade from black to the selected color instead of from the color to black within the single strand effect.  While keeping the number of cycles built in to the single strand effect already.    Also added tooltips for the single strand panel. #4603

### CODE REVIEW

**Comment by computergeek1507** [comment]
Gross more checkboxes

**Comment by derwin12** [comment]
Brian .. seems you need a little help from the admins to allow your code to compile... @computergeek1507

**Comment by sidelights** [comment]
that would be great what I can do to help make that happen?

**Comment by dkulp** [comment]
I kind of agree that another checkbox for this doesn't make sense.  I think I'd prefer that the "Fade" turns into a choice with a few options of {"None", "Tail", "Head", "Both"}.   That would require a bit more work as the older sequences would need to be updated.

**Comment by sidelights** [comment]
With additional options it would be better as a choice.  I was only considering adding the reverse fade originally, and that would just be something new not requiring any conversion to existing sequences.   It made more sense as an additional box because it only would exist when you had 3d fade enabled, then flip it.  Adding additional options like both or even reverse both (logically) would be better in a drop down.    I was also pondering the bars effect and the spiral which also has similar logic for 3d fade and if that would be 'nice' there or not.     I figured instead of just saying to a developer hey I think this would be neat, could you make it for me, I would try to contribute help as well instead of just ideas.  

With the options described then it turns into the following I believe:
new 'FADE From Choice box (default none) -- existing 3d fade box unchecked. 
Choices: 
New name   -   OLD name  -   visual for communication here  (from left to right) maybe in a tool tip? 
------------ 
"None"              -  n/a unchecked -     n/a
"From Head"            -   3d fade            -    ++---------
"From Tail"               -   3d reversed      -    ---------++
"Head and Tail"        -   n/a aka both    -    ++ --- ++
"Middle"                 -    n/a                   -    ---+++---


Also I could not trigger a way to get the non- alpha buffer blend (HSV) to trigger in the code.  Does anyone know what causes that logic path to be available.  If I'm going to rewrite to allow additional options I would like to know how to trigger hsv so it can be validated well.

**Comment by sidelights** [comment]
I can be in the zoom room tonight after 7pm central if you want to demo what you are talking about Gil.  I attempted to do what I think you are attempting to describe and I could not get it to do what I can do with the additional fade options proposed with increasing options under the existing 3d fade functionality in the single strand.  But I'm happy to learn something new if I missing something. 
Thanks!

**Comment by dkulp** [comment]
> It will depend on how the effect is using the feature. Search for IsSpatial and GetSpatialColor to find the effects that support it. It can be added to effects that don't utilize it.

.... with the caveat that as soon as spacial colors are used, rendering on the GPU is not possible at this point so it's stuck rendering on the CPU.

**Comment by sidelights** [comment]
single strand does have spacial, and using the -> or <- against the color does fade the direction with a gradient over the chase length.  However the HEAD of the single strand when in reverse (faded out) overlays the tail causing a black 3rd pattern over the single strand.  see video comparing the reversed 3d fade (head dark to tail bright), and 3d fade (orig - head bright tail dark), and the reversed 3d fade , to the color fade spatial as you mentioned
[rervese 3d fade vs spatial - Copy.zip](https://github.com/user-attachments/files/15828899/rervese.3d.fade.vs.spatial.-.Copy.zip)
.   Basically it looks like it keeps the 'head' as the most prominent pixel.

**Pull request closed without merging**
