### PR TITLE
Added ability to save color palette with a name

### PR DESCRIPTION
**Pull request by derwin12**
#3902 additional box that can optionally be entered. Nothing fancy .. just a name that is stripped of any funny characters.
Thoughts on the layout?
image
image

### CODE REVIEW

**Comment by computergeek1507** [comment]
I think it makes the GUI messy looking, I think "renaming" pallets has a minor use case and shouldn't be front and center to every user

**Comment by derwin12** [comment]
> I think it makes the GUI messy looking, I think "renaming" pallets has a minor use case and shouldn't be front and center to every user

What about a popup when you click the save icon? I tossed around a couple of ideas on zoom. With this implementation .. the default window has it fall off the right and you dont even know its there :-) which is a good thing for many.

**Comment by derwin12** [comment]
Change up the UI a bit..
image

**Comment by derwin12** [comment]
Change up the GUI just a bit..
image

**Comment by cybercop23** [comment]
@computergeek1507 are you okay with this new layout? It's stacked as to not make the top section wider and seems to "flow" more naturaly.

**Comment by dkulp** [comment]
I'm not.  I don't see the point in having the palette name field there at all.

**Comment by computergeek1507** [comment]
I think it has a limited use case and is not needed. Not all feature requests have to be fulfilled.

**Pull request closed without merging**
