### PR TITLE
ILightThat controllers: Add new board

### PR DESCRIPTION
**Pull request by PeteMatthews**

### CODE REVIEW

**Comment by computergeek1507** [comment]
should it be a dmx port not a pixel port?

**Comment by PeteMatthews** [comment]
> should it be a dmx port not a pixel port?

You're absolutely right - committed from wrong repo clone. Apologies.

The controller plugin doesn't need amending - It already supplies all the config this board needs.

Thanks :)

**Comment by patdelaney** [comment]
@PeteMatthews What are  ILightThat controllers?

**Comment by computergeek1507** [comment]
The Baldrick Controllers buildalightshow.com, Gilbert Engineering, Wired Watts are selling.

**Pull request merged**
