### PR TITLE
Add preference to override color highlighting #3446

### PR DESCRIPTION
**Pull request by derwin12**
The preference can be used to override the cyan/blue color in lists and another to override the grey/med grey. #3446

### CODE REVIEW

**Comment by derwin12** [comment]
Any thoughts on why the ::instance fails on Ubuntu?

**Comment by computergeek1507** [comment]
Utils fiction needs an include to wxcolor, your auto is really a wxcolor which isn't defined in the utils class

**Comment by derwin12** [comment]
I am on windows .. compiles fine -- so yea -- some lib missing on the unix side?
utils did get the colormanager.h included.

**Comment by derwin12** [comment]
I committed the change from auto. 
I suppose xSchedule never used color preferences? I need to test this change in xSchedule. It might not use the color preferences at all which this would sort of mean it has to or atleast it has to access them.

**Comment by derwin12** [comment]
xSchedule compile did indeed fail on windows.

**Comment by derwin12** [comment]
Okay .. the cleanest answer here is to remove my wedge in the utils function and keep that clean for xschedule and such.
I will close the PR and rething/recode that.

**Pull request closed without merging**
