### PR TITLE
New Controllers from GalloTech

### PR DESCRIPTION
**Pull request by Gallosauro**
Added new Controllers from GalloTech.
WLED compatible with ESP32, ESP32-C3, and Esp8266 chip.
First Pull request is very open to comments, and suggestions, of any kind so please let me know if any revision is required. 

Thanks,
GalloTech

### CODE REVIEW

**Comment by MrPaulAR** [comment]
Why does the WLED controller not work for this if it's "WLED compatible"?

**Review by derwin12 — COMMENTED** [review]
How is this different than the current WLED controller?
Is there a website for this controller?

**Comment by cybercop23** [comment]
At best, this should be a Model under the WLED Vendor and not a vendor. You copied all of the WLED code and just changed the name. NO. There's also no difference in pinouts so it can/should be just streight WLED Vendor & Model.
image

**Comment by computergeek1507** [comment]
Please provide information about your controller and the company behind it. We do not add controllers from unknown brands until there is some of a user base in our community. If it is a WLED based controller, no new upload class is needed, it should use the existing WLED code I wrote.

**Comment by Gallosauro** [comment]
Thanks for the answers, there is not company behind yet, I made 3 controllers that are in the testing phase. 
the controllers works with the WLED software, one is a micro with only one port, one with 6 ports and one with 8 port and LCD. the pinout is slightly different than the one pointed out from Cybercop23. I did not know I could add them under WLED, my bad, it is the first time I add something in github.

**Pull request closed without merging**
