### PR TITLE
Scale the sphere to get a good 3d model export #3931

### PR DESCRIPTION
**Pull request by derwin12**
Using the same technique done for 2d to find the scale factor to get a complete 3d export of the sphere. Also include the dimensions if available. #3931

### CODE REVIEW

**Comment by cybercop23** [comment]
People with the power.. can this please me merged?

**Comment by derwin12** [comment]
Just want to add after seeing Alex's comments .. that merging in means we can get some nightly builds in to test them by many folks .. no rush to put out to production at all.

**Comment by computergeek1507** [comment]
I did try this at one point but it makes the custom models x^3 times bigger per iteration and then the custom dialog is super slow

**Comment by computergeek1507** [comment]
I think the twinkly has the same issue, I was thinking that Gils float based multipoint model or maybe a way to allow two nodes in the same location on a custom model as a better solution then just making the models huge.

**Comment by cybercop23** [comment]
> Just want to add after seeing Alex's comments .. that merging in means we can get some nightly builds in to test them by many folks .. no rush to put out to production at all.

Couldn't said it better myself. Selfishly since I'm on TestFlight, I just get the latest eveynight.. so I'm good and happy to test.

**Comment by derwin12** [comment]
> I think the twinkly has the same issue, I was thinking that Gils float based multipoint model or maybe a way to allow two nodes in the same location on a custom model as a better solution then just making the models huge.

My first attempt it did .. I found going from 2 (the original code) .. most of my attempts worked at 3 or 4. So not overly big < 100x100 in the custom model. It wasnt that much of an impact. Another one of those things that I doubt is used all that often.

**Pull request merged**
