### PR TITLE
#4292 Add preference to disable submodel dup node check

### PR DESCRIPTION
**Pull request by derwin12**
Similar to preference to disable duplicate nodes in model groups.
Issue #4292

### CODE REVIEW

**Comment by keithsw1111** [comment]
I disagree with this. While model groups it is hard to prevent duplicates I can’t see any reason why you would do this in a submodel.

On 24 Jan 2024, at 11:36 am, Daryl ***@***.***> wrote:

﻿

Similar to preference to disable duplicate nodes in model groups.
Issue #4292<https://github.com/xLightsSequencer/xLights/issues/4292>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/xLightsSequencer/xLights/pull/4293

Commit Summary

  *   fe753fc<https://github.com/xLightsSequencer/xLights/pull/4293/commits/fe753fc277aca79da8025422d0e3bbef26b1a6a2> #4292 Add preference to disable submodel dup node check

File Changes

(4 files<https://github.com/xLightsSequencer/xLights/pull/4293/files>)

  *   M xLights/preferences/CheckSequenceSettingsPanel.cpp<https://github.com/xLightsSequencer/xLights/pull/4293/files#diff-2ea406a249e1fdf3e3a42bfdcec78d8ee73c559808d518d85abffe1aba50d6ed> (15)
  *   M xLights/preferences/CheckSequenceSettingsPanel.h<https://github.com/xLightsSequencer/xLights/pull/4293/files#diff-e81ee4891932d689589fa14999ad67e56ae37d561e068c9b35e9e34922e6f7c1> (3)
  *   M xLights/wxsmith/CheckSequenceSettingsPanel.wxs<https://github.com/xLightsSequencer/xLights/pull/4293/files#diff-aeed7f787551ef23a6cabf891141030496d2bc91f65a8f9bab176c2ea817cb94> (11)
  *   M xLights/xLightsMain.cpp<https://github.com/xLightsSequencer/xLights/pull/4293/files#diff-692facf05a050f4bde1e42db38106f55ee53ade6e8bfc97dc0903547dcd73c14> (29)

Patch Links:

  *   https://github.com/xLightsSequencer/xLights/pull/4293.patch
  *   https://github.com/xLightsSequencer/xLights/pull/4293.diff

**Comment by derwin12** [comment]
A sub model of arms might have the first pixel in common or share a common
edge. Dups in sub models are very common.

**Comment by derwin12** [comment]
Here is mine for example .. 
This way once your show is set and layout done, you can hide the noise and focus on the check sequence, sequence issues.
Most folks pull in models anyways and dont have a clue what this means and think its an issue. They can see it or with this option atleast hide it after reviewing them.
image

**Comment by cybercop23** [comment]
Since this is now "protected" by an option and not on by default, the user(s) can easily choose which options works/fits best for them.

**Comment by AzGilrock** [comment]
@keithsw1111 are you still against this one going in?  Looks like it has an option to disable/enable it.

**Comment by keithsw1111** [comment]
I am. I don’t think submodels should allow it without warning. Submodels are essentially custom buffers and duplicate nodes have no place in them. Unlike groups where the user can’t really do much about it there is no reason not to fix this.

On 26 Jan 2024, at 12:46 pm, Gil Jones ***@***.***> wrote:

﻿

@keithsw1111<https://github.com/keithsw1111> are you still against this one going in? Looks like it has an option to disable/enable it.

**Comment by AzGilrock** [comment]
Ok maybe I was confused on what we were saying here.  So your saying inside a single submodel there should be no duplicate nodes.   That’s sounds reasonable.  I thought we were talking about the same node in different submodels for the same parent model.  Guess I need to hear why duplicate nodes in the same submodel are a common thing.

**Comment by derwin12** [comment]
A single submodel .. made up where each line makes up an arm in a spinner will show duplicate nodes if they share a single pixel in the center. A single arm - sure .. no duplicates - but that gets lost in this duplicates. Perhaps the dup node check needs a little tweak and allow duplicate nodes in the various lines. With this change - a user can go thru their list, get the dups and then can ignore  the rest. 
Here is the showstopper spinner for eg.
image
It is this noise.. Turning off these preferences are sort of advanced feature.
image

**Comment by dkulp** [comment]
Kind of wonder if this could/should be a submodel specific setting.  "Acknowledge duplicate nodes" kind of thing.

**Comment by cybercop23** [comment]
With this change it is. The current one allows you to ignore duplicates at the group level, but this one was to allow at the sub-model level. As @derwin12 indicated, this is realy not a duplicate per-say. More and more folks are using submodels to create "stacked"/multi-line sub-models so the duplicates are across multiple, indvidual rows and not on the same row.

**Comment by dkulp** [comment]
No, this change makes it a GLOBAL setting affecting all submodels.   I'm suggesting make it specific to EACH submodel and saved in the rgbeffects as part of the submodel.    Thus, if you do introduce duplicate nodes, you will still get a warning OR you would need to acknowledge for that model that it is intentional.

**Comment by merryoncherry** [comment]
It's funny, I have 1200 duplicate node in submodel warnings in my layout and not a single person out of the thousands of viewers has ever come up to me and said, "Hey MoC, you know your show would be a lot better if you spent a few hours cleaning up the duplicate nodes in your submodels".  I have actually noticed that I have a duplicate node, but only once out of 14 hours of material I ran last year.

It's quite common in stranded submodels.
It's quite common in vendor models you get straight from downloads in the xLights model download dialog.

Here's a list of the 95 models (out of 1136) that have submodels with duplicate nodes provided by the vendor:
Dups in: Boscoyo LLS 35
Dups in: Toms-Holdman Star
Dups in: Boscoyo_SarahFlake_23
Dups in: ChromaMan
Dups in: Halloween_Tree_v2_1
Dups in: Diamond_Tip_ChromaFlake_23in
Dups in: Diamond_Tip47_Chromaflake
Dups in: Fire_Department_Shield
Dups in: Boscoyo_BellFlower
Dups in: Boscoyo Ice Queen Snowflake
Dups in: Boscoyo_Mesmerizer
Dups in: PPD Wreath V5
Dups in: Boscoyo_Singing_Bunny_Head
Dups in: Boscoyo_Train_Caboose_wSubs
Dups in: Boscoyo_Train_Engine
Dups in: Boscoyo_Train_Matrix_wSubs
Dups in: Boscoyo_Train_Bulbs_wSubs
Dups in: Boscoyo_Train_Candy_Cane_wSubs
Dups in: Boscoyo_Train_Presents_wSubs
Dups in: Boscoyo_Train_Snowflake_wSubs
Dups in: Boscoyo_Train_Trees_Subs_1
Dups in: Candy_Corn_Stalk
Dups in: Ornament 5
Dups in: Reindeer_Crossing_2
Dups in: Boscoyo_Gingerbread_Man2
Dups in: Boscoyo_Gingerbread_Woman2
Dups in: Spinner 23 inch Right
Dups in: Ditto Sign
Dups in: Boscoyo_Gnome_Snowflake
Dups in: Beetlejuice
Dups in: Jack
Dups in: Horror_Head_Jason
Dups in: Leatherface
Dups in: Michael
Dups in: Pennywise
Dups in: Boscoyo Mega Black Widow
Dups in: Boscoyo Santa Motor Cycle
Dups in: Mini_at_Sea_Helm_Finished
Dups in: Boscoyo HDPE Spider Web
Dups in: The Insane Cane 1
Dups in: GE Insane Pole
Dups in: DAVIDCROSS_final
Dups in: FUSION
Dups in: InfinitySpinner-Showstopper
Dups in: Mandala36Flake_Showstopper
Dups in: Ornament3
Dups in: PeppermintDual
Dups in: LargeFlake600
Dups in: Snowflake_Small
Dups in: TriangleOfPower100
Dups in: VISIONARY 300
Dups in: VISIONARY 450 V2
Dups in: Owl wreath
Dups in: Toombstone RIP Cross
Dups in: Custom
Dups in: EFL Snowman
Dups in: EFL Snowman with motor
Dups in: Pixie_Wings-3
Dups in: 03.15.0Mod Showstopper Snowflake
Dups in: 03.16.0Mod Showstopper Spinner
Dups in: 32Cane
Dups in: Wing
Dups in: GE Carrier
Dups in: GE Caboose
Dups in: GE Candle Family
Dups in: GE Coal Car
Dups in: GE Dazzler 1
Dups in: Gilbert Engineering Dream Catcher
Dups in: GE Flake G1
Dups in: GE Flake H-157
Dups in: GE Flake I 36
Dups in: GE Franken Monster (2)
Dups in: GE Fuzion
Dups in: GE Insane Arch
Dups in: GE Insane Cane 1
Dups in: GE Kalidescope
Dups in: GE Gloves
Dups in: GE Magical Singing Mousette
Dups in: GE Spinarchy Mini 1
Dups in: GE Passenger Car - Matrix
Dups in: GE Rosa Grande 1
Dups in: GE Rosa Tomb 1
Dups in: GE Railroad Crossing Sign
Dups in: Pimp 4
Dups in: Rainbow
Dups in: GE Snowman 8 ft
Dups in: GE 8ft Snowman Singing
Dups in: GE Space Oddesy
Dups in: GE SpinReel Max 36
Dups in: GE Spiro
Dups in: GE Squared 1
Dups in: GE 640
Dups in: GE Steam Locomotive
Dups in: GE Sunflower
Dups in: GE Nutcracker Singing

While I'm on the soapbox, a 27 vendor models also have submodels with node numbers outside the range of the model:
Outside in: Turtle_2
Outside in: Boscoyo ChromaBulb 30 Hanging
Outside in: Boscoyo ChromaGlow Present Sml
Outside in: Boscoyo 3d 4 foot tree
Outside in: Singing Tree 3
Outside in: Boscoyo Santa Motor Cycle
Outside in: Gothic-Arch
Outside in: BethlehemStarMini
Outside in: EFL Fan
Outside in: 03.16.0Mod Showstopper Spinner
Outside in: GE Battle Cross No Tags
Outside in: GE BOAW
Outside in: GE Candle Joy
Outside in: GE Dazzler 1
Outside in: GE - Grad Cap w-matrix
Outside in: GE Dreidel G
Outside in: GE Dreidel S
Outside in: GE_Lollipop_Sm
Outside in: GE_Mouse
Outside in: GE_Rainbow_1137
Outside in: GE Stable Vixen
Outside in: Crossing Railroad Gate
Outside in: GE Railroad Crossing Sign
Outside in: GE Snowman Matrix No Spinner V2
Outside in: GE Snowman No Matrix Spinner V2
Outside in: GE 640
Outside in: GE Big Boo Singing

Is it really so wrong to want to suppress this one warning, so you can see all the useful stuff check sequence has to offer?

I'll be including the patch in the builds I make for myself... thanks for providing it @derwin12.

**Comment by AzGilrock** [comment]
Really no excuse to have them in the same sub model.  If it’s the center pixel of an arm then take that one out before you duplicate it 20 times then just have one line with the center pixel by itself.  It’s one sub model it’s not like we are lighting up those rows individually

**Comment by derwin12** [comment]
> Really no excuse to have them in the same sub model. If it’s the center pixel of an arm then take that one out before you duplicate it 20 times then just have one line with the center pixel by itself. It’s one sub model it’s not like we are lighting up those rows individually

But you do .. single strand goes around and lights up each petal/spoke etc .. That's why dups are needed.

**Comment by AzGilrock** [comment]
Ok I see what you mean.  I’m not gonna mind either way I never run check sequence

**Comment by cybercop23** [comment]
Right.. this is only an "issue"/annoyance... since some of the coro vendors are doing proper submodeling....
They will not be duplicate of they were split, actually they already are but there's also a Join one.

image

**Comment by derwin12** [comment]
Perhaps if I create another ticket to for an additional check sequence to
flag duplicate nodes on line items. Not sure how to term that.
That should indeed be cleaned up.
Like    eg.
1-10,5,6,5

**Comment by cybercop23** [comment]
Been waiting for this. Any reason why this can't be merged... please....

**Comment by dkulp** [comment]
> Been waiting for this. Any reason why this can't be merged... please....

As mentioned, this PR puts this as a global level setting which is not appropriate for it.   It needs to be redone as a submodel level checkbox on the submodel dialog.

**Comment by cybercop23** [comment]
I closed my original request for the Preference option, since @derwin12 made the change to do it at the layer level, which was a better way to address this ==> https://github.com/xLightsSequencer/xLights/pull/4317. - hoping this can be merged now and the several other PRs ready.

**Comment by keithsw1111** [comment]
I still dont get it. I dont mind a node appearing in different submodels but it does not belong in a single submodel. It does not do what you think it does and the user should be aware of that.

The spinner example is a rubbish example. You are thinking the node is duplicated on each line ... and it isnt ... only one of those instances actually works ... all the others get silently removed. This is not acceptable.

This is fundamentally wrong and the sooner this is closed the better.

**Comment by dkulp** [comment]
Closing this PR as it's not how it's needed.

**Comment by cybercop23** [comment]
Agreed. Replaced by: #4316

**Pull request closed without merging**
