### PR TITLE
Tweak the State Dialog to avoid squished buttons #4749

### PR DESCRIPTION
**Pull request by derwin12**
Set min size for the slider panel so it doesnt start of squished #4749

### CODE REVIEW

**Comment by computergeek1507** [comment]
400, my 640x480 CRT won't like that

**Comment by derwin12** [comment]
I assume you are joking .. what does it look like now .. it must be unusable then.

**Comment by derwin12** [comment]
Min size for these buttons to show poperly
image

**Comment by computergeek1507** [comment]
mine only does this small with the current master code
image

**Comment by derwin12** [comment]
Confirmed .. I will close this out.. not sure why mine was messed up... perhaps I didnt get the latest commits.

**Pull request closed without merging**
